name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Roswell
      env:
        LISP: ${{ matrix.lisp }}
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/v22.12.14.113/scripts/install-for-ci.sh | sh
    - name: Run test
      run: |
        set -ex

        ros config set dynamic-space-size 2048

        ros install lem-project/async-process lem
        ros install cxxxr/sblint fukamachi/rove

        export PATH=$HOME/.roswell/bin:$PATH

        sblint src/base/lem-base.asd
        sblint lem.asd
        sblint lib/lisp-syntax/lem-lisp-syntax.asd
        sblint modes/lisp-mode/lem-lisp-mode.asd
        sblint lib/micros/micros.asd

        rove lem-tests.asd
